// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const prismaDir = path.join(__dirname, "prisma");

export default defineConfig({
  schema: path.join(prismaDir, "schema.prisma"),
  migrations: {
    path: path.join(prismaDir, "migrations"),
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
